set(Plugin-ActivationPolicy "eager")
set(Plugin-Name "pluginSL3")
set(Plugin-Version "1.0.0")
set(Plugin-Description "Test plugin for framework, pluginSL3_test")
set(Plugin-Vendor "CommonTK")
set(Plugin-ContactAddress "http://www.commontk.org")
set(Plugin-Category "test")
set(Require-Plugin pluginSL1.test)
