FROM thewtex/opengl:v0.1.0
MAINTAINER Insight Software Consortium <community@itk.org>

RUN REPO=http://cdn-fastly.deb.debian.org && \
  echo "deb $REPO/debian jessie main\ndeb $REPO/debian jessie-updates main\ndeb $REPO/debian-security jessie/updates main" > /etc/apt/sources.list

RUN apt-get update && apt-get install -y \
  qttools5-dev \
  libqt5xmlpatterns5-dev \
  wget && \
  rm -rf /var/lib/apt/lists/*

RUN wget https://cmake.org/files/v3.7/cmake-3.7.1-Linux-x86_64.tar.gz && \
  tar -xzf cmake-3.7.1-Linux-x86_64.tar.gz && \
  rsync -avz cmake-3.7.1-Linux-x86_64/ /usr/local

ENV APP "sudo chown -R user.user /usr/src/ && /usr/src/CTK/CMake/CircleCI/test.sh -DCTK_QT_VERSION:STRING=5"
