FROM thewtex/opengl:v0.1.0
MAINTAINER Insight Software Consortium <community@itk.org>

RUN REPO=http://cdn-fastly.deb.debian.org && \
  echo "deb $REPO/debian jessie main\ndeb $REPO/debian jessie-updates main\ndeb $REPO/debian-security jessie/updates main" > /etc/apt/sources.list

RUN apt-get update && apt-get install -y \
  qt4-dev-tools \
  cmake \
  && rm -rf /var/lib/apt/lists/*

ENV APP "sudo chown -R user.user /usr/src/ && /usr/src/CTK/CMake/CircleCI/test.sh -DCTK_QT_VERSION:STRING=4"
