repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.4.0"
  hooks:
  - id: check-added-large-files
    args: ['--maxkb=1024']
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
    exclude: "\\.(svg|vtk|vtp)$"
