set(CTEST_PROJECT_NAME "CTK")
set(CTEST_NIGHTLY_START_TIME "23:00:00 EDT")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "my.cdash.org")
set(CTEST_DROP_LOCATION "/submit.php?project=CTK")
set(CTEST_DROP_SITE_CDASH TRUE)
