set(Plugin-ActivationPolicy "eager")
set(Plugin-Name "Framework Registry Performance Test Suite")
set(Plugin-Version "0.9")
set(Plugin-Description "Test the performance of the service registry")
set(Plugin-Vendor "CommonTK")
set(Plugin-DocURL "http://www.commontk.org")
set(Plugin-ContactAddress "http://www.commontk.org")
set(Plugin-Category "test")
set(Plugin-Copyright "German Cancer Research Center, Division of Medical and Biological Informatics")
set(Plugin-License "http://www.apache.org/licenses/LICENSE-2.0.html")
