set(Plugin-ActivationPolicy "eager")
set(Plugin-Name "framework_test")
set(Plugin-Version "1.0.1")
set(Plugin-Description "Test bundle for the CTK plugin framework")
set(Plugin-Vendor "CommonTK")
set(Plugin-DocURL "http://www.commontk.org")
set(Plugin-ContactAddress "http://www.commontk.org")
set(Plugin-Category "test")
set(Plugin-Copyright "German Cancer Research Center, Division of Medical and Biological Informatics")
set(Plugin-License "http://www.apache.org/licenses/LICENSE-2.0.html")
