set(Plugin-ActivationPolicy "eager")
set(Plugin-Name "app_test")
set(Plugin-Version "0.1")
set(Plugin-Description "Test plugin for framework, app_test")
set(Plugin-Vendor "CommonTK")
set(Plugin-ContactAddress "http://commontk.org")
set(Plugin-Category "test")
