set(Plugin-ActivationPolicy "eager")
set(Plugin-Name "pluginSL4")
set(Plugin-Version "1.0.0")
set(Plugin-Description "Test plugin for framework, pluginSL4_test")
set(Plugin-Vendor "CommonTK")
set(Plugin-ContactAddress "http://commontk.org")
set(Plugin-Category "test")
set(Require-Plugin pluginSL1.test)
