set(Plugin-ActivationPolicy "eager")
set(Plugin-Name "pluginA_test")
set(Plugin-Version "1.0.0")
set(Plugin-Description "Test plugin for framework, pluginA_test")
set(Plugin-Vendor "CommonTK")
set(Plugin-ContactAddress "http://commontk.org")
set(Plugin-Category "test")
