#
# See CMake/ctkMacroAddCtkLibraryOptions.cmake
#
# This file should list of options available for considered CTK library
# For example: MYOPT1:OFF MYOPT2:ON
#

set(ctk_library_options
  PYTHONQT_USE_VTK:OFF
  PYTHONQT_WRAP_QTALL:OFF
  PYTHONQT_WRAP_QTCORE:OFF
  PYTHONQT_WRAP_QTGUI:OFF
  PYTHONQT_WRAP_QTWIDGETS:OFF
  PYTHONQT_WRAP_QTNETWORK:OFF
  PYTHONQT_WRAP_QTOPENGL:OFF
  PYTHONQT_WRAP_QTPRINTSUPPORT:OFF
  PYTHONQT_WRAP_QTSQL:OFF
  PYTHONQT_WRAP_QTSVG:OFF
  PYTHONQT_WRAP_QTUITOOLS:OFF
  PYTHONQT_WRAP_QTWEBKIT:OFF
  PYTHONQT_WRAP_QTWEBKITWIDGETS:OFF
  PYTHONQT_WRAP_QTXML:OFF
  PYTHONQT_WRAP_QTXMLPATTERNS:OFF
  )
